version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: dacom-logs-mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dacomlogs
      MYSQL_USER: dacom
      MYSQL_PASSWORD: 123Mudar@
    volumes:
      - dacom_logs_mysql_data:/var/lib/mysql

volumes:
  dacom_logs_mysql_data:
